apiVersion: v1
kind: Service
metadata:
  name: fetch-data
spec:
  selector:
    app: fetch-data
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500  # Exposed to host machine
  type: NodePort
