apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deployer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "update", "delete", "get", "list", "watch"]
